version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=roleplay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:yourpassword@db:5432/roleplay
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=0
      - ALLOWED_HOSTS=*

volumes:
  postgres_data:
  redis_data: