version: '3.8'

services:
  web:
    build: .
    command: uvicorn roleplay.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=roleplay.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
